version: '3.9'

services:
  ecomm:
    build: .
    container_name: app-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: $HOST/C:/Users/gabir/OneDrive/Documentos/NxtDev/ecomm
        target: /mongo-scripts
    restart: always
    ports:
      - 27017:27017

volumes:
  db-mongo-ecomm: