openapi: 3.0.0
info:
  title: API de Produtos
  version: 1.0.0
paths:
  /api/categories:
    get:
      summary: Listagem de categorias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '404':
            description: Categoria não encontrada.
            content:
              application/json:
                example: "Not Found"
  /api/admin/categories:
    post:
      summary: Inserção de categorias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /api/categories/{id}:
    get:
      summary: Detalhamento de categoria
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID da categoria
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
            description: Categoria não encontrada.
            content:
              application/json:
                example: "Not Found"
    put:
      summary: Atualizar dados de uma categoria (apenas para administradores)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da categoria a ser atualizada
        - in: body
          name: body
          required: true
          description: Dados da categoria a serem atualizados
          schema:
            $ref: '#/components/schemas/Categoria'
      responses:
        '200':
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
        '401':
          description: Acesso não autorizado (não é um administrador)
        '404':
          description: Categoria não encontrada
        '500':
          description: Erro interno do servidor

    delete:
      summary: Remover uma categoria (apenas para administradores)
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID da categoria a ser removida
      responses:
        '204':
          description: Categoria removida com sucesso
        '401':
          description: Acesso não autorizado (não é um administrador)
        '404':
          description: Categoria não encontrada
        '500':
          description: Erro interno do servidor
          
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          description: ID da categoria
        nome:
          type: string
          description: Nome da categoria
        status:
          type: string
          description: Status da categoria
    CategoryInput:
      type: object
      properties:
        nome:
          type: string
          description: Nome da categoria
        status:
          type: string
          description: Status da categoria
