openapi: 3.0.0
info:
  title: API de Produtos
  version: 1.0.0
paths:
  /api/categories:
    get:
      summary: Listagem de categorias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
        '404':
            description: Categoria não encontrada.
            content:
              application/json:
                example: "Not Found"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          description: ID da categoria
        nome:
          type: string
          description: Nome da categoria
        status:
          type: string
          description: Status da categoria